header:
  license:
    content: |
      Copyright (c) 2023-2024 Datalayer, Inc.

      BSD 3-Clause License

  paths-ignore:
    - '**/*.ipynb'
    - '**/*.json'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.md'
    - '**/.*'
    - 'LICENSE'

  comment: on-failure
