name: Build

on:
  push:
    branches: ["main"]
  pull_request:

defaults:
  run:
    shell: bash -eux {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install the extension
        run: |
          python -m pip install ".[test]"

      - name: Test the extension
        run: |
          pytest tests --cov=jupyter_mimetypes --cov-report=xml --cov-report=html --cov-report=term-missing

      - name: Build the extension
        run: |
          pip install build
          python -m build --sdist
          cp dist/*.tar.gz my_package.tar.gz
          pip uninstall -y "jupyter_mimetypes"
          rm -rf "jupyter_mimetypes"

      - uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: my_package-sdist-${{ matrix.python-version }}
          path: my_package.tar.gz

  check_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1

  test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Run Linters
        run: |
          bash ./.github/workflows/lint.sh
